Repository genexuslabs/JavaClasses, pull requests merged in 2023-07, with the labels that each got.

#738 Security fixes, close open steams
  common/src/main/java/com/genexus/GXJarClassLoader.java
  common/src/main/java/com/genexus/GXParameterPacker.java
  common/src/main/java/com/genexus/ImagesPath.java
  common/src/main/java/com/genexus/Messages.java
  common/src/main/java/com/genexus/URLRouter.java
  common/src/main/java/com/genexus/internet/GXHttpClient.java
  common/src/main/java/com/genexus/reports/ParseINI.java
  common/src/main/java/com/genexus/util/GXFileInfo.java
  common/src/main/java/com/genexus/util/IniFile.java
  common/src/main/java/com/genexus/util/Rijndael_Properties.java
  common/src/main/java/com/genexus/util/Twofish_Properties.java
  common/src/main/java/com/genexus/xml/XMLReader.java
  gxcloudstorage-googlecloudstorage/src/main/java/com/genexus/db/driver/ExternalProviderGoogle.java
  gxcryptocommon/src/main/java/com/genexus/cryptography/GXCertificate.java
  gxmail/src/main/java/com/genexus/internet/POP3SessionJavaMail.java
  gxmail/src/main/java/com/genexus/internet/SMTPSession.java
  gxoffice/src/main/java/com/genexus/gxoffice/poi/hssf/ExcelDocument.java
  gxoffice/src/main/java/com/genexus/gxoffice/poi/sxssf/ExcelDocument.java
  java/src/main/java/com/genexus/GXReorganization.java
  java/src/main/java/com/genexus/PrivateUtilities.java
  java/src/main/java/com/genexus/db/driver/GXConnection.java
  java/src/main/java/com/genexus/db/driver/GXDBDebug.java
  java/src/main/java/com/genexus/db/driver/GXPreparedStatement.java
  java/src/main/java/com/genexus/db/driver/GXResultSet.java
  java/src/main/java/com/genexus/internet/HttpRequestWeb.java
  java/src/main/java/com/genexus/internet/HttpResponse.java
  java/src/main/java/com/genexus/util/GXFile.java
  java/src/main/java/com/genexus/util/JavaInspector.java
  java/src/main/java/com/genexus/webpanels/HttpUtils.java
Labels: conflict

#741 [OpenTelemetry] Add Exception Details when Error ocurrs in REST Service execution
  common/pom.xml
  common/src/main/java/com/genexus/opentelemetry/OpenTelemetryHelper.java
  java/pom.xml
  pom.xml
  wrappercommon/src/main/java/com/genexus/WrapperUtils.java
Labels: conflict

#753 Change BouncyCastle reference in Android.
  android/pom.xml
Labels: tested

#755 Bump jtidy library to version 1.0.4
  gxsearch/pom.xml
Labels: dependencies
